### ISSUE TITLE
Server sends static transaction ID on broadcasts, clients see it as a duplicate packet

### ISSUE THREAD

**Issue by domstyle** [MakeICT/electronic-door#19]
Because the clients see all broadcast messages as having the same ID, they only process the first one and ignore all following messages.

We should either
- Modify the server so that it doesn't use a static transaction ID on broadcast messages
- Modify the clients so that they process all broadcast messages

IMO, broadcast messages should work sorta like UDP. Clients shouldn't acknowledge them, clients should process all broadcast messages (that are applicable), server should not attempt resends on broadcasts.

**Comment by Rowbotronics** [comment]
Client code was updated to ignore transaction ID on broadcast packets and not send an ACK.  All broadcast messages will be processed.
