### ISSUE TITLE
Make client respond to pings and change displays after timeout

### ISSUE THREAD

**Issue by domstyle** [MakeICT/electronic-door#25]
Clients should ACK ping messages
When a client hasn't received a ping in a while, it should update it's LCD and LED displays with some identifiable message

**Comment by Rowbotronics** [comment]
Here's how I plan to implement this:
- Clients will have a timeout set ( 1 minute?)
- If no valid packets are received from the server in that time, LEDs and LCD will be changed to indicate disconnect.  Heartbeats only need to be sent if no other data is sent within the timeout period.
- Once a valid packet is received the client will send a start packet
- At that point the server should update the clients LCD and LEDs

Sound good?

**Comment by domstyle** [comment]
Makes sense to me!

Does the server need to send both an LCD and LED message though? If it just sends the LCD message, the client  will no longer be in a longer-than-60s state, so it can resume it's default LED behavior.

**Comment by Rowbotronics** [comment]
This has been implemented with the following change: Clients resume default LED sequence upon receiving any new message from the server.  They don't have a default LCD message, so that still needs to be reset.  Or we could make some kind of default.
