### ISSUE TITLE
Log when alarm button is pressed

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/electronic-door#28]
Would be nice to now if/when the alarm is being armed.

**Comment by domstyle** [comment]
There should be messages in the log (as of just earlier today). A log message is generated when the arm or disarm command is sent to the alarm system, and another log message is generated when the system reports that it's armed status has changed.

**Comment by Rowbotronics** [comment]
It looks like it only logs messages from the alarm decoder plugin, so there isn't any info about which client's button was pressed.  It would be good to know where the alarm got armed from.

**Comment by domstyle** [comment]
It was logging when armed from the UI and not from clients, but now it should be logging both. It still doesn't log which client sent the arm message though.

**Comment by domstyle** [comment]
Fixed
