### ISSUE TITLE
Require key scan to arm alarm

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/electronic-door#29]
This would allow us to log who arms the alarm, and prevent accidental arming.

**Comment by domstyle** [comment]
Tricky. I'm afraid that some people would just stop bothering with it altogether. I think a lot of people already don't.

I think if we generate noise on the chimes when the alarm has been armed, it would allow people time to go disarm it if they are still in the building. This will be most effective with chimes in every area.

**Comment by Rowbotronics** [comment]
Yeah, that would help.  Have a tone that plays every 10-20 seconds until the alarm is fully set.

**Comment by Rowbotronics** [comment]
I think the pre-alarm tone is sufficient to prevent unintentional arming/triggering of the alarm.  We probably don't need to know who armed it, just that it got armed.
