### ISSUE TITLE
Add log filter options

### ISSUE THREAD

**Issue by poguepotamus** [MakeICT/electronic-door#39]
Can there be a log somewhere that only displays the log of keys that are given? This would be useful to assign application forms and making a 20 min task automatic. Thanks!

**Comment by domstyle** [comment]
Can you be more specific about what exactly you'd want to see in this?

**Comment by poguepotamus** [comment]
I just want specifically the two events:
-When someone is assigned a key. When the key is actually being paired with the member object?
-When someones key is disabled and removed from a members account. 
-When someones key is designated "lost" and removed from a members account.

This can be in working progress with making the 'lost key' function that we were talking about. This specifically is to be used when assigning names to key forms, if I know when the keys were assigned, and I have the PDF if the correct order, then it makes assigning them take a few seconds instead of a few dozen minutes.

**Comment by Rowbotronics** [comment]
Log filtering was added in c7bd3ed9021194ad81715af81d058b43b4fdb9a1 and finally is in a usable state in 58fd2775d65396c652d6323076620fb5d406fb6a. Will be merged into Master shortly.
