### ISSUE TITLE
Add a tag search

### ISSUE THREAD

**Issue by poguepotamus** [MakeICT/electronic-door#49]
Add the ability to search for tags like "back-door" or "admin-closet" along with the ability to search for groups.

**Comment by domstyle** [comment]
More specifically, you want to search for _users_ who belong to any group which has authorization on a given tag, correct?

Searching for users based on group is already implemented. Ex: group:administrators

**Comment by poguepotamus** [comment]
Yes

**Comment by domstyle** [comment]
You can now search for users who belong to a group which has been granted an authorization tag using:
`tag:tag-name`

You can also click on the tag name from the groups page.
