### ISSUE TITLE
Username link in log should open user's info, not e-mail link

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/electronic-door#50]
The current behavior seems counter-intuitive to me.  I think it makes more sense to open the user info, then send an e-mail from there if necessary.  I usually just want to check the user's group and status if a key is getting rejected.

**Comment by poguepotamus** [comment]
Plz help

**Comment by domstyle** [comment]
Clicking a name in the log now links to a search on the user's page by the user's email address.
