### ISSUE TITLE
Can't download systemd log

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/electronic-door#52]
When trying to download the systemd log from from the system tools plugin, the console will give the "Systemd Log Generated" message, but it doesn't open the log or start a download.

**Comment by domstyle** [comment]
It should open in a new tab. You may need to whitelist the domain in your
pop-up blocker.


*Dominic Canare*
Technology Consultant, Green Light Go
316.461.3981

**Comment by Rowbotronics** [comment]
You're right.  Chrome's pop-up blocker is so subtle I didn't even notice it.  I had the old domain name whitelisted, but not the new one.
